# Generated by Django 3.0.8 on 2020-07-16 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doner_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='IMG_20200309_064310.jpg', null=True, upload_to='users/'),
        ),
    ]
