# Generated by Django 3.0.8 on 2020-07-19 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doner_profile', '0005_auto_20200718_1504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='Last_Donation_Date',
        ),
        migrations.AddField(
            model_name='profile',
            name='Last_Donation_Date_Year_Month_Day',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Age',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Blood_Group',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Phone_Number',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Present_Address',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Profile_Image',
            field=models.ImageField(blank=True, default='800px-Blood_donation_pictogram.svg.png', null=True, upload_to='users/'),
        ),
    ]
