# Generated by Django 3.0.8 on 2020-07-19 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doner_profile', '0006_auto_20200719_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Email',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
