# Generated by Django 3.0.8 on 2020-08-04 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doner_profile', '0009_remove_profile_last_donation_date_year_month_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Last_Donation_Date_Year_Month_Day',
            field=models.DateField(blank=True, null=True),
        ),
    ]
