# Generated by Django 3.0.8 on 2020-08-04 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doner_profile', '0010_profile_last_donation_date_year_month_day'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Last_Donation_Date_Year_Month_Day',
            new_name='Last_Donation_Date',
        ),
    ]
