# Generated by Django 3.0.8 on 2020-08-06 03:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('doner_profile', '0011_auto_20200804_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Blood_Group',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Gender',
            field=models.CharField(choices=[('male', 'MALE'), ('female', 'FEMALE')], max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Profession',
            field=models.CharField(blank=True, choices=[('Student', 'student'), ('Service', 'service'), ('Job seeker', 'job seeker'), ('Housewife', 'housewife'), ('Others', 'others')], max_length=50),
        ),
    ]
